[package]
name = "pqc_crypto_bench"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
oqs = "0.11.0"
rand = "0.8"

[[bench]]
name = "primitives_benchmark"
harness = false
